2-task sorts array
js-tasks-ru/js-20210309-2_artha-di pull request #2
Opened 2021-03-13 12:54 UTC by arthadi

task sorting new array

2021-03-13 12:54 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-14 14:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (arr.length !== 0) {
эта проверка здесь лишняя

2021-03-14 14:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const arrayArg = arr.slice().sort();
что происходит в данной строке? 
для чего вызов метода `sort()`?

2021-03-14 14:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      newArraySort.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-03-14 14:15 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const functionArguments = fields;
`functionArguments` это не совсем корректное имя, более того не понятно зачем происходит переприсваивание `fields` в переменную с другим имененм

2021-03-14 14:15 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let i = 0; i < functionArguments.length; i++) {
подумайте, можно ли избавиться от циклов `for`?

2021-03-14 14:15 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
аналогичные замечания как в задании `pick`

2021-03-14 14:16 UTC, dosandk requested changes
необходимо дать ответы на вопросы, внести правки согласно комментариям

2021-03-14 18:23 UTC, arthadi commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const arrayArg = arr.slice().sort();
Я не знал как отсортировать массив чтобы первыми вставали слова с заглавных букв. Sort() без атрибутов делает такую сортировку. После этого нужно было конечно еще сортировать учитывая диакретические знаки. И поэтому еще одна сортировка, что ниже и т. д. Не лучшее конечно но решение). Еще раз перечитал главу по сортировке с помощью localeCompare Погуглил где только можно, вроде разобрался. Обновленная версия конечно красотуля)) Компактна, хорошо читается.

2021-03-14 18:27 UTC, arthadi commented on 02-javascript-data-types/2-pick/index.js
> +  for (let i = 0; i < functionArguments.length; i++) {
Можно избавиться с помощью .map() но ведь там тоже итерация только внутри?

2021-03-16 20:10 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const arrayArg = arr.slice();
альтернативный способ скопировать массив:
```
const copy = [...arr];
```

2021-03-16 20:11 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let direction = (param === 'asc') ? 1 : -1;
проверьте, тут точно `let`?

2021-03-16 20:11 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return a.localeCompare(b, ['ru', 'en'], { caseFirst: 'upper'}) * direction;
good 👍

2021-03-16 20:11 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
good 👍

2021-03-16 20:11 UTC, dosandk approved these changes

2021-03-16 20:12 UTC, merged